BEGIN;

ALTER TABLE sources ADD COLUMN IF NOT EXISTS verifier_type VARCHAR(20) NOT NULL DEFAULT 'noop';
ALTER TABLE sources ADD COLUMN IF NOT EXISTS verifier_cfg JSONB;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

COMMIT;
