BEGIN;

ALTER TABLE sources ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL DEFAULT '';

UPDATE sources SET name = slug WHERE name = '';

ALTER TABLE sources ALTER COLUMN name DROP DEFAULT;

COMMIT;
